---
title: "Pricing Analytics Store Locations"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(glmnet)
library(ISLR)
library(dplyr)
library(ggplot2)
SafeBabies <- Carseats %>% select("Sales", "Price", "ShelveLoc")
Good<-subset(SafeBabies, ShelveLoc=="Good")
Medium<-subset(SafeBabies, ShelveLoc=="Medium")
Bad<-subset(SafeBabies, ShelveLoc=="Bad")
```

```{r}
#Defining the Formula for the regressions
formula=Sales~Price
```

```{r}
#Determining The Optimal Price For Good Shelf Locations
Good_Model <- glm(formula = formula, family = "gaussian", data = Good)
Coeff_Good<-data.frame(Good_Model$coefficients, stringsAsFactors = TRUE)
Left_Good <- matrix(c(2*Coeff_Good[c(2), ]),nrow=1,ncol=1)
Right_Good <- matrix(c(Coeff_Good[c(2), ]*55 +Coeff_Good[c(1), ]-Coeff_Good[c(1), ]*55),nrow=1,ncol=1)
solve(Left_Good, Right_Good)
```

```{r}
#Determining The Optimal Price For Medium Shelf Locations
Medium_Model <- glm(formula = formula, family = "gaussian", data = Medium)
Coeff_Medium<-data.frame(Medium_Model$coefficients, stringsAsFactors = TRUE)
Left_Medium <- matrix(c(2*Coeff_Medium[c(2), ]),nrow=1,ncol=1)
Right_Medium <- matrix(c(Coeff_Medium[c(2), ]*55 +Coeff_Medium[c(1), ]-Coeff_Medium[c(1), ]*55),nrow=1,ncol=1)
solve(Left_Medium, Right_Medium)
```

```{r}
#Determining The Optimal Price For Bad Shelf Locations
Bad_Model <- glm(formula = formula, family = "gaussian", data = Bad)
Coeff_Bad<-data.frame(Bad_Model$coefficients, stringsAsFactors = TRUE)
Left_Bad <- matrix(c(2*Coeff_Bad[c(2), ]),nrow=1,ncol=1)
Right_Bad <- matrix(c(Coeff_Bad[c(2), ]*55 +Coeff_Bad[c(1), ]-Coeff_Bad[c(1), ]*55),nrow=1,ncol=1)
solve(Left_Bad, Right_Bad)
```

```{r}
#Plotting the Optimal Shelf Locations When Production Costs Vary For Good, Medium, and Bad Locations
#Good Locations
data<- c()
v <- c(40:85)
for ( i in v) {
  Left_Good <- matrix(c(2*Coeff_Good[c(2), ]),nrow=1,ncol=1)
Right_Good <- matrix(c(Coeff_Good[c(2), ]*i +Coeff_Good[c(1), ]-Coeff_Good[c(1), ]*i),nrow=1,ncol=1)
value<-solve(Left_Good, Right_Good) 
  data<-append(data, value)
}
Good_Prices <- data.frame(Production_Costs=v, Optimal_Prices=data, Location="Good")
```

```{r}
#Medium Locations
data<- c()
v <- c(40:85)
for ( i in v) {
  Left_Medium <- matrix(c(2*Coeff_Medium[c(2), ]),nrow=1,ncol=1)
Right_Medium <- matrix(c(Coeff_Medium[c(2), ]*i +Coeff_Medium[c(1), ]-Coeff_Medium[c(1), ]*i),nrow=1,ncol=1)
value<-solve(Left_Medium, Right_Medium) 
  data<-append(data, value)
}
Medium_Prices <- data.frame(Production_Costs=v, Optimal_Prices=data, Location="Medium")
#Plot For Medium Locations

```

```{r}
#Bad Locations
data<- c()
v <- c(40:85)
for ( i in v) {
  Left_Bad <- matrix(c(2*Coeff_Bad[c(2), ]),nrow=1,ncol=1)
Right_Bad <- matrix(c(Coeff_Bad[c(2), ]*i +Coeff_Bad[c(1), ]-Coeff_Bad[c(1), ]*i),nrow=1,ncol=1)
value<-solve(Left_Bad, Right_Bad) 
  data<-append(data, value)
}
Bad_Prices <- data.frame(Production_Costs=v, Optimal_Prices=data, Location="Bad")


```

```{r}
#Plot For Locations
#The prices increase as production costs increase. However, it is apparent that the slope for good locations
#is steeper than the bad locations, which makes sense since there is likely diminishing returns involved with raising #prices in bad locations.
Prices<- rbind(Good_Prices, Medium_Prices, Bad_Prices)
Plot<- ggplot(data = Prices, aes(x = Production_Costs, y = Optimal_Prices, col=Location)) + geom_line() + geom_point()+labs(title="Optimal Prices by Production Costs by Shelf Location")
Plot
```
